name: main
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'raspberry.zip'
        exclusions: '*.git* LICENSE'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "raspberry.zip"
        token: ${{ secrets.GITHUB_TOKEN }}

          
