name: main
on:
  push:
    branches:
      - 'main'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@main
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'raspberry.zip'
        exclusions: '*.git* LICENSE'
    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "raspberry.zip"

          
