name: main
on:
  push:
    branches:
      - 'main'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@main
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'raspberry.zip'
        exclusions: '*.git* LICENSE'
    - name: Get current date
      id: date
      run: echo echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    - name: Create Tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "raspberry.zip"
        makeLatest: true
        token:  ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.tag_version.outputs.new_tag }}

          
