name: main
on:
  push:
    branches:
      - 'main'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@main
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'raspberry.zip'
        exclusions: '*.git* LICENSE'
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Create Tag
      uses: laputansoft/github-tag-action@v4.6
      with:
        github_token: ${{ env.github-token }}
        tag: versoin-${{ steps.date.outputs.date }}
    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "raspberry.zip"
        makeLatest: true
        token:  ${{ secrets.GITHUB_TOKEN }}

          
